default: &default
  adapter: postgresql
  encoding: unicode
  username: postgresql
  password: 123456
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nome_do_seu_projeto_development

test:
  <<: *default
  database: nome_do_seu_projeto_test

production:
  primary: &primary_production
    <<: *default
    database: job_search_production
    username: job_search
    password: <%= ENV["JOB_SEARCH_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: job_search_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: job_search_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: job_search_production_cable
    migrations_paths: db/cable_migrate
